# Netlify CMS

The [Netlify CMS](https://netlifycms.org) is an open source content management solution for use with static sites like Hugo. It provides a graphical interface to managing content that is particularly useful for people who are not comfortable with working with Git.

To achieve the goal of enabling anyone with a GitHub account to submit content (for approval!) to our website, we can add the CMS to a Hugo website hosted in GitHub and deployed to Netlify by:

1. Copy the [starter files](https://www.netlifycms.org/docs/add-to-your-site/#app-file-structure) to `static/admin` 
2. Add `<script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>` to the template/partial that includes the `<head>` tag
3. Add `<script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>` to the `static/admin/index.html` file in the `<head>` tag
4. Create an [OAuth Github app](https://github.com/settings/developers) that includes the following:
  + Authorization callback url: https://api.netlify.com/auth/done
5. Add the Github OAuth provider via the Access Control settings (URL like https://app.netlify.com/sites/<SITENAME>/settings/access), using the id and secret generated by GitHub.
6. Make sure the Git Gateway is connected to Github (URL like https://app.netlify.com/sites/<SITENAME>/settings/identity)
7. Configure the `static/admin/config.yaml` to include:

```yaml
publish_mode: editorial_workflow
backend:
  name: github
  repo: <org>/<repo>
  open_authoring: true
```

## Configuring the CMS
The `config.yaml` provides the configuration for the whole CMS. Using YAML, we can rapidly generate appropriate interfaces for different content types that need to be added to our website and provide validation rules to ensure values are completed correctly.

```yaml
collections:
  - name: 'posts'
    label: 'Blog posts'
    folder: 'content/posts'
    create: true
    fields:
      - label: "Blog title"
        name: "title"
        widget: "string"
        required: true
      - label: "Publish date"
        name: "date"
        widget: "datetime"
        required: true
      - label: "Post content"
        name: "body"
        widget: "markdown"
        required: true
```